version: '3.4'

services:
  processhandler:
    image: processhandler
    build:
      context: src/apps/apis/process-handler
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
